//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapterTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChapterTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_drop_down {
            get {
                object obj = ResourceManager.GetObject("arrow_drop_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_drop_up {
            get {
                object obj = ResourceManager.GetObject("arrow_drop_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_All {
            get {
                return ResourceManager.GetString("File_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有支持的类型 的本地化字符串。
        /// </summary>
        internal static string File_Filter_All_Support {
            get {
                return ResourceManager.GetString("File_Filter_All_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 章节文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_Chapter_File {
            get {
                return ResourceManager.GetString("File_Filter_Chapter_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cue文件[包括内嵌] 的本地化字符串。
        /// </summary>
        internal static string File_Filter_Cue_File {
            get {
                return ResourceManager.GetString("File_Filter_Cue_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matroska文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_Matroska_File {
            get {
                return ResourceManager.GetString("File_Filter_Matroska_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mp4文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_Mp4_File {
            get {
                return ResourceManager.GetString("File_Filter_Mp4_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_Text {
            get {
                return ResourceManager.GetString("File_Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebVTT文件 的本地化字符串。
        /// </summary>
        internal static string File_Filter_VTT_File {
            get {
                return ResourceManager.GetString("File_Filter_VTT_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件还没载入呢 的本地化字符串。
        /// </summary>
        internal static string File_Unloaded {
            get {
                return ResourceManager.GetString("File_Unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击了 {0} 次进度条 的本地化字符串。
        /// </summary>
        internal static string Log_About_Form_Click {
            get {
                return ResourceManager.GetString("Log_About_Form_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条点击计数清零 的本地化字符串。
        /// </summary>
        internal static string Log_About_Form_Click_Reset {
            get {
                return ResourceManager.GetString("Log_About_Form_Click_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开了关于界面 的本地化字符串。
        /// </summary>
        internal static string Log_About_Form_Opened {
            get {
                return ResourceManager.GetString("Log_About_Form_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}次启动 Chapter Tool. 的本地化字符串。
        /// </summary>
        internal static string Log_Boot_Count {
            get {
                return ResourceManager.GetString("Log_Boot_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +载入自定义章节名模板: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Chapter_Name_Template {
            get {
                return ResourceManager.GetString("Log_Chapter_Name_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色设置窗口被打开 的本地化字符串。
        /// </summary>
        internal static string Log_Color_Setting_Form_Open {
            get {
                return ResourceManager.GetString("Log_Color_Setting_Form_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   |+包含 {0} 个时间戳 的本地化字符串。
        /// </summary>
        internal static string Log_Convert_TimeStamp_Count {
            get {
                return ResourceManager.GetString("Log_Convert_TimeStamp_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+自动帧率识别开始，允许误差为: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_FPS_Detect_Begin {
            get {
                return ResourceManager.GetString("Log_FPS_Detect_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  | {0:D2} 个精确点 的本地化字符串。
        /// </summary>
        internal static string Log_FPS_Detect_Count {
            get {
                return ResourceManager.GetString("Log_FPS_Detect_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |自动帧率识别结果为 {0:F4} fps 的本地化字符串。
        /// </summary>
        internal static string Log_FPS_Detect_Result {
            get {
                return ResourceManager.GetString("Log_FPS_Detect_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬盘壕，给我块硬盘呗~ 的本地化字符串。
        /// </summary>
        internal static string Log_Hard_Drive_Plz {
            get {
                return ResourceManager.GetString("Log_Hard_Drive_Plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 你好呀 的本地化字符串。
        /// </summary>
        internal static string Log_Hello {
            get {
                return ResourceManager.GetString("Log_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+IFO中共有 {0} 个VOB片段 的本地化字符串。
        /// </summary>
        internal static string Log_IFO_Clip_Count {
            get {
                return ResourceManager.GetString("Log_IFO_Clip_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从运行参数中载入文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Load_File_Via_Args {
            get {
                return ResourceManager.GetString("Log_Load_File_Via_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从载入键中载入文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Load_File_Via_Button {
            get {
                return ResourceManager.GetString("Log_Load_File_Via_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从窗口拖拽中载入文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Load_File_Via_Dragging {
            get {
                return ResourceManager.GetString("Log_Load_File_Via_Dragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +成功载入保存的窗体位置 {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Load_Position_Successful {
            get {
                return ResourceManager.GetString("Log_Load_Position_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用的 libmp4v2.dll, 是否前往下载页面 的本地化字符串。
        /// </summary>
        internal static string Log_Mp4v2_Not_Find {
            get {
                return ResourceManager.GetString("Log_Mp4v2_Not_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+MPLS中共有 {0} 个m2ts片段 的本地化字符串。
        /// </summary>
        internal static string Log_MPLS_Clip_Count {
            get {
                return ResourceManager.GetString("Log_MPLS_Clip_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +成功载入MPLS格式章节文件 的本地化字符串。
        /// </summary>
        internal static string Log_MPLS_Load_Success {
            get {
                return ResourceManager.GetString("Log_MPLS_Load_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +更名: {0} -&gt; {1} 的本地化字符串。
        /// </summary>
        internal static string Log_Rename {
            get {
                return ResourceManager.GetString("Log_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率:  的本地化字符串。
        /// </summary>
        internal static string Log_Resolution {
            get {
                return ResourceManager.GetString("Log_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + {0} 行(i = {1})被删除 的本地化字符串。
        /// </summary>
        internal static string Log_Row_Delete {
            get {
                return ResourceManager.GetString("Log_Row_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+章节号平移: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Chapter_Order_Shift {
            get {
                return ResourceManager.GetString("Log_Save_Chapter_Order_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+对应视频文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Correspond_File {
            get {
                return ResourceManager.GetString("Log_Save_Correspond_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+保存文件名: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_File_Name {
            get {
                return ResourceManager.GetString("Log_Save_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +保存信息 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Info {
            get {
                return ResourceManager.GetString("Log_Save_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+使用章节名: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Is_Use_Chapter_Name {
            get {
                return ResourceManager.GetString("Log_Save_Is_Use_Chapter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  |+使用章节名模板: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Is_Use_Chapter_Name_Template {
            get {
                return ResourceManager.GetString("Log_Save_Is_Use_Chapter_Name_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   |+语言选择: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Language {
            get {
                return ResourceManager.GetString("Log_Save_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+章节开始时间 x 1.001: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Time_Factor {
            get {
                return ResourceManager.GetString("Log_Save_Time_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+时间平移: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Time_Shift {
            get {
                return ResourceManager.GetString("Log_Save_Time_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  |+平移量: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Time_Shift_Amount {
            get {
                return ResourceManager.GetString("Log_Save_Time_Shift_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  |+保存格式: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Save_Type {
            get {
                return ResourceManager.GetString("Log_Save_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置保存路径为: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Set_Saving_Path {
            get {
                return ResourceManager.GetString("Log_Set_Saving_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   |+包含 {0} 个时间戳 的本地化字符串。
        /// </summary>
        internal static string Log_TimeStamp_Count {
            get {
                return ResourceManager.GetString("Log_TimeStamp_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已检查更新 的本地化字符串。
        /// </summary>
        internal static string Log_Update_Checked {
            get {
                return ResourceManager.GetString("Log_Update_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过更新检查 的本地化字符串。
        /// </summary>
        internal static string Log_Update_Skiped {
            get {
                return ResourceManager.GetString("Log_Update_Skiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 噫，有权限( •̀ ω •́ )y，可以瞎搞了 的本地化字符串。
        /// </summary>
        internal static string Log_With_Admin {
            get {
                return ResourceManager.GetString("Log_With_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哎，木有权限，好伤心 的本地化字符串。
        /// </summary>
        internal static string Log_Without_Admin {
            get {
                return ResourceManager.GetString("Log_Without_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武总好~ 的本地化字符串。
        /// </summary>
        internal static string Log_Wu_Zong {
            get {
                return ResourceManager.GetString("Log_Wu_Zong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |+XPL中共有 {0} 个片段 的本地化字符串。
        /// </summary>
        internal static string Log_XPL_Clip_Count {
            get {
                return ResourceManager.GetString("Log_XPL_Clip_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 {0} 的本地化字符串。
        /// </summary>
        internal static string Menu_Open_File {
            get {
                return ResourceManager.GetString("Menu_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChapterTool Error 的本地化字符串。
        /// </summary>
        internal static string Message_ChapterTool_Error {
            get {
                return ResourceManager.GetString("Message_ChapterTool_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChapterTool Information 的本地化字符串。
        /// </summary>
        internal static string Message_ChapterTool_Info {
            get {
                return ResourceManager.GetString("Message_ChapterTool_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好呀，找到这里来干嘛呀 的本地化字符串。
        /// </summary>
        internal static string Message_How_Can_You_Find_Here {
            get {
                return ResourceManager.GetString("Message_How_Can_You_Find_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 Chapter Tool 打开 .mpls 文件？ 的本地化字符串。
        /// </summary>
        internal static string Message_Open_With_CT {
            get {
                return ResourceManager.GetString("Message_Open_With_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存调用堆栈至剪切板？ 的本地化字符串。
        /// </summary>
        internal static string Message_Stack {
            get {
                return ResourceManager.GetString("Message_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取MP4文件信息异常 的本地化字符串。
        /// </summary>
        internal static string Message_Unable_To_Read_Mp4_File {
            get {
                return ResourceManager.GetString("Message_Unable_To_Read_Mp4_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前片段并没有章节 (¬_¬) 的本地化字符串。
        /// </summary>
        internal static string Tips_Chapter_Not_find {
            get {
                return ResourceManager.GetString("Tips_Chapter_Not_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 {0} 个片段 的本地化字符串。
        /// </summary>
        internal static string Tips_Clip_Count {
            get {
                return ResourceManager.GetString("Tips_Clip_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IFO格式的章节，已自动*1.001，如需取消请手动操作 的本地化字符串。
        /// </summary>
        internal static string Tips_IFO_Waring_Fixed {
            get {
                return ResourceManager.GetString("Tips_IFO_Waring_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IFO格式的章节，请注意是否需要修正时间 的本地化字符串。
        /// </summary>
        internal static string Tips_IFO_Waring_Unfix {
            get {
                return ResourceManager.GetString("Tips_IFO_Waring_Unfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位移时间不科学的样子 的本地化字符串。
        /// </summary>
        internal static string Tips_Invalid_Shift_Time {
            get {
                return ResourceManager.GetString("Tips_Invalid_Shift_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个文件我不认识啊 _ (:3」∠)_ 的本地化字符串。
        /// </summary>
        internal static string Tips_InValid_Type {
            get {
                return ResourceManager.GetString("Tips_InValid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式非法 的本地化字符串。
        /// </summary>
        internal static string Tips_InValid_Type_Log {
            get {
                return ResourceManager.GetString("Tips_InValid_Type_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入失败… 的本地化字符串。
        /// </summary>
        internal static string Tips_Load_Fail {
            get {
                return ResourceManager.GetString("Tips_Load_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入完成 (≧▽≦) 的本地化字符串。
        /// </summary>
        internal static string Tips_Load_Success {
            get {
                return ResourceManager.GetString("Tips_Load_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入中，请稍候… 的本地化字符串。
        /// </summary>
        internal static string Tips_Loading {
            get {
                return ResourceManager.GetString("Tips_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这应该是播放菜单的mpls 的本地化字符串。
        /// </summary>
        internal static string Tips_Menu_Clip {
            get {
                return ResourceManager.GetString("Tips_Menu_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的序号超出范围 的本地化字符串。
        /// </summary>
        internal static string Tips_Out_Of_Range {
            get {
                return ResourceManager.GetString("Tips_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string Tips_Save_Fail {
            get {
                return ResourceManager.GetString("Tips_Save_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string Tips_Save_Success {
            get {
                return ResourceManager.GetString("Tips_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二个章节点离视频结尾太近了呢，应该没有用处吧 (-｡-;) 的本地化字符串。
        /// </summary>
        internal static string ToolTips_Useless_Chapter {
            get {
                return ResourceManager.GetString("ToolTips_Useless_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap unfold_more {
            get {
                object obj = ResourceManager.GetObject("unfold_more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string Update_Check {
            get {
                return ResourceManager.GetString("Update_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将内容复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string Zones_Copy_To_Clip_Board {
            get {
                return ResourceManager.GetString("Zones_Copy_To_Clip_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先将模式调至帧数取整 的本地化字符串。
        /// </summary>
        internal static string Zones_Set_Round_First {
            get {
                return ResourceManager.GetString("Zones_Set_Round_First", resourceCulture);
            }
        }
    }
}
