//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChapterTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChapterTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前片段并没有章节 (¬_¬) 的本地化字符串。
        /// </summary>
        internal static string Chapter_Not_find {
            get {
                return ResourceManager.GetString("Chapter_Not_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChapterTool Error 的本地化字符串。
        /// </summary>
        internal static string ChapterTool_Error {
            get {
                return ResourceManager.GetString("ChapterTool_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChapterTool Information 的本地化字符串。
        /// </summary>
        internal static string ChapterTool_Info {
            get {
                return ResourceManager.GetString("ChapterTool_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件还没载入呢 的本地化字符串。
        /// </summary>
        internal static string File_Unloaded {
            get {
                return ResourceManager.GetString("File_Unloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬盘壕，给我块硬盘呗~ 的本地化字符串。
        /// </summary>
        internal static string Hard_Drive_Plz {
            get {
                return ResourceManager.GetString("Hard_Drive_Plz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 你好呀 的本地化字符串。
        /// </summary>
        internal static string Helloo {
            get {
                return ResourceManager.GetString("Helloo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好呀，找到这里来干嘛呀 的本地化字符串。
        /// </summary>
        internal static string How_Can_You_Find_Here {
            get {
                return ResourceManager.GetString("How_Can_You_Find_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IFO格式的章节，请注意是否需要修正时间 的本地化字符串。
        /// </summary>
        internal static string IFO_WARNING {
            get {
                return ResourceManager.GetString("IFO_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个文件我不认识啊 _ (:3」∠)_ 的本地化字符串。
        /// </summary>
        internal static string InValid_Type {
            get {
                return ResourceManager.GetString("InValid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式非法 的本地化字符串。
        /// </summary>
        internal static string InValid_Type_Log {
            get {
                return ResourceManager.GetString("InValid_Type_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从窗口拖拽中载入文件: 的本地化字符串。
        /// </summary>
        internal static string Load_File_By_Dragging {
            get {
                return ResourceManager.GetString("Load_File_By_Dragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功载入保存的窗体位置 的本地化字符串。
        /// </summary>
        internal static string Load_Position_Successful {
            get {
                return ResourceManager.GetString("Load_Position_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入完成 (≧▽≦) 的本地化字符串。
        /// </summary>
        internal static string Load_Success {
            get {
                return ResourceManager.GetString("Load_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 Chapter Tool 打开 .mpls 文件？ 的本地化字符串。
        /// </summary>
        internal static string Open_With_CT {
            get {
                return ResourceManager.GetString("Open_With_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率： 的本地化字符串。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武总好~ 的本地化字符串。
        /// </summary>
        internal static string Ye_Zong {
            get {
                return ResourceManager.GetString("Ye_Zong", resourceCulture);
            }
        }
    }
}
